#!/bin/bash

###############################################################################
#
#   An utility script to checking which Java version compiled each submodule
#   of this project.
#
###############################################################################

echo "===================================================="
echo "Verifying Java version for classes within JAR files."
echo ""
echo "  jakarta-validation-extensions must be 55 (Java 11)"
echo ""
echo "Note that JAR files must exist (./gradlew build)."
echo ""

echo "===== jakarta-validation-extensions ===="
javap \
    -verbose \
    -classpath build/libs/jakarta-validation-extensions-*-SNAPSHOT.jar \
    io.github.malczuuu.lib.jakarta.validation.ext.OneOfValidator \
    | grep "major version"
