name: Gradle Snapshot (Manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (must match vX.Y.Z)'
        required: true
        default: 'v1.0.0'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Validate version input
        run: |
          if [[ ! "${{ github.event.inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format. Must match vX.Y.Z"
            exit 1
          fi

      - name: Publish Snapshot with Gradle Wrapper
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          PUBLISHING_USERNAME: ${{ secrets.PUBLISHING_USERNAME }}
          PUBLISHING_PASSWORD: ${{ secrets.PUBLISHING_PASSWORD }}
        run: |
          BASE_VERSION="${{ github.event.inputs.version }}"
          SNAPSHOT_VERSION="${BASE_VERSION#v}-SNAPSHOT"  # removes leading 'v' from tag name
          echo "Publishing snapshot version $SNAPSHOT_VERSION"
          ./gradlew -Pversion="$SNAPSHOT_VERSION" -Psign publishAllPublicationsToCentralPortalSnapshots
